export { default as Home  } from './Home'
export { default as About  } from './About'
export { default as Items  } from './Items'
export { default as Payment  } from './Payment'
export { default as Quotes  } from './Quotes'